export * from "./box";
export * from "./button";
export * from "./confirmation-dialog";
export * from "./icon";
export * from "./image";
export * from "./inline-text";
export * from "./link";
export * from "./paragraph";
export * from "./separator";
export * from "./switch";
export * from "./title";
export { default as Box } from "./box";
export { default as Button } from "./button";
export { default as ConfirmationDialog } from "./confirmation-dialog";
export { default as Icon } from "./icon";
export { default as Image } from "./image";
export { default as InlineText } from "./inline-text";
export { default as Link } from "./link";
export { default as Paragraph } from "./paragraph";
export { default as Separator } from "./separator";
export { default as Switch } from "./switch";
export { default as Title } from "./title";
